// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW3zAaIOHxw-DU7ulBFIwqXb-YT0Cb1hI',
    appId: '1:280044368064:web:cd27948682497103b4fd25',
    messagingSenderId: '280044368064',
    projectId: 'crud-deber',
    authDomain: 'crud-deber.firebaseapp.com',
    databaseURL: 'https://crud-deber-default-rtdb.firebaseio.com',
    storageBucket: 'crud-deber.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgYAld9tMG4GAOD3Uv2azfkj2DI4kh9ro',
    appId: '1:280044368064:android:8fd8b12b2f4eae97b4fd25',
    messagingSenderId: '280044368064',
    projectId: 'crud-deber',
    databaseURL: 'https://crud-deber-default-rtdb.firebaseio.com',
    storageBucket: 'crud-deber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSpxTrfsjeXImDFJKMciacCafjzmEsET0',
    appId: '1:280044368064:ios:295168d2dedc94c7b4fd25',
    messagingSenderId: '280044368064',
    projectId: 'crud-deber',
    databaseURL: 'https://crud-deber-default-rtdb.firebaseio.com',
    storageBucket: 'crud-deber.firebasestorage.app',
    iosBundleId: 'com.example.deberCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSpxTrfsjeXImDFJKMciacCafjzmEsET0',
    appId: '1:280044368064:ios:295168d2dedc94c7b4fd25',
    messagingSenderId: '280044368064',
    projectId: 'crud-deber',
    databaseURL: 'https://crud-deber-default-rtdb.firebaseio.com',
    storageBucket: 'crud-deber.firebasestorage.app',
    iosBundleId: 'com.example.deberCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW3zAaIOHxw-DU7ulBFIwqXb-YT0Cb1hI',
    appId: '1:280044368064:web:ad2b95050a8ee4ffb4fd25',
    messagingSenderId: '280044368064',
    projectId: 'crud-deber',
    authDomain: 'crud-deber.firebaseapp.com',
    databaseURL: 'https://crud-deber-default-rtdb.firebaseio.com',
    storageBucket: 'crud-deber.firebasestorage.app',
  );

}